### ISSUE TITLE
events should be part of PushSubscription 

### ISSUE THREAD

**Issue by ShijunS** [w3c/push-api#104]
The spec allows a webapp to create a push subscription without using a Service Worker, and the PushSubscription object will persist as long as the webapp window is open.  The "push" and "pushsubscriptionlost" events should be defined as part of PushSubscription in order for that to work.  The events are currently defined as extension to ServiceWorkerGlobalScope.

**Comment by mvano** [comment]
The spec depends on Service Workers, e.g. see the first paragraph of the abstract:

> A push service allows a webapp server to send messages to a webapp, regardless of whether the webapp is currently active on the user agent. The push message will be delivered to a Service Worker[...]

This enables the following part of the use case section [1]:

> the webapp is not currently active in a browser window: this relates to use cases in which the user may close the webapp, but still benefits from the webapp being able to be restarted when a push message is received

The `PushManager` is only exposed on `ServiceWorkerRegistration` for this reason:
https://w3c.github.io/push-api/#extensions-to-the-serviceworkerregistration-interface

Without Service Workers the user agent would have to spin up a web page, with most likely far higher CPU, memory, and network requirements.

https://w3c.github.io/push-api/#introduction

**Comment by ShijunS** [comment]
The spec has the following when defining the "Push Subscription Persistence":

> If a webapp creates a push subscription without using a Service Worker, the PushSubscription object will persist only as long as the webapp window is open. 

From the API perspective, the spec should keep the consistency.  There is no conflict to the scenarios where the webapp is not active.

**Comment by mvano** [comment]
There are still some inconsistencies in the document, I think you found one here. My apologies, the spec is still in Draft state.

I'd like to step back and ask you what your goal is. The most important difference between the Push API and Server-sent Events [1][2] is in supporting this use case:

> the webapp is not currently active in a browser window: this relates to use cases in which the user may close the webapp, but still benefits from the webapp being able to be restarted when a push message is received

If this does not fit your use case, why not use Server-sent Events?

[1] https://html.spec.whatwg.org/multipage/comms.html#server-sent-events
[2] http://www.html5rocks.com/en/tutorials/eventsource/basics/

**Comment by martinthomson** [comment]
> If this does not fit your use case, why not use Server-sent Events?

I have an easy answer for that: Server-sent Events is an abomination that should be exterminated.

**Comment by mvano** [comment]
Martin, do you have any further detail on the drawbacks of Server-sent Events?

**Comment by martinthomson** [comment]
At risk of derailing this thread...  The major drawback is the abuse of HTTP.

SSE assumes that there is a clean channel between the origin and the client, without any intermediary that could alter the timing of packet delivery.  That assumption has been proven false in a great many deployments.

For instance, SSE fails where there is a virus-scanning intermediary.  Those buffer HTTP entities so that they can verify that they are clean.

**Comment by mvano** [comment]
I see. However, on the benefits side, Server-sent events are already quite widely implemented and deployed:
http://caniuse.com/#search=eventsource

**Comment by martinthomson** [comment]
http://caniuse.com/#feat=websockets

**Comment by mvano** [comment]
Yep, that also seems like a reasonable solution for the foreground use case. And it has Internet Explorer support :-)

**Comment by mvano** [comment]
As there are existing alternatives while running in the foreground (Server-sent Events, Web Sockets) I'll close this issue, there is no need to make this change in the Push API.
