### ISSUE TITLE
Refer to reusable definition of PermissionDeniedError once that becomes available

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#107]
There is an open bug for defining PermissionDeniedError [1] and once it is defined the Push API should just refer to that.

[1] https://www.w3.org/Bugs/Public/show_bug.cgi?id=23033

**Comment by jyasskin** [comment]
https://github.com/heycam/webidl/pull/116 changed WebIDL to say to use NotAllowedError for this: http://heycam.github.io/webidl/#notallowederror
