### ISSUE TITLE
Remove PushManager#hasPermission in favor of Permissions API

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#109]
The Permissions API [1] is likely to provide a generalized way to check the permission status of a large number of APIs, including the Push API. It seems likely we can omit the PushManager#hasPermission method from the Push API.

Talking as a Chrome implementer, I think we might initially ship without hasPermission for this reason, to wait and see if the Permissions API gains sufficient momentum in the near term.

[1] https://w3c.github.io/permissions/

**Comment by martinthomson** [comment]
Not that I'm a fan of the permissions API, but what would be the upshot of this?  Would applications have to look for an exception/rejection to determine if permission wasn't granted?

**Comment by mvano** [comment]
Yes, the subscribe method [1] would reject with PermissionDeniedError:
https://w3c.github.io/push-api/#widl-PushManager-subscribe-Promise-PushSubscription

It seems we can avoid having this soon-to-be redundant method.

CC @mounirlamouri

**Comment by mounirlamouri** [comment]
:+1:

**Comment by mvano** [comment]
With my Chrome hat on, I'm now happy to actually ship the hasPermission method. With the addition of `PushSubscriptionOptions.userVisible` all the semantic problems have been resolved.

Also, while the Permissions API has shipped in Chrome, other vendors have not committed to it yet to the same extent as the Push API. I'd rather not wait for it further.

With these thoughts, I withdraw my suggestion to remove `hasPermission`.
