### ISSUE TITLE
Any implementation ?

### ISSUE THREAD

**Issue by vasilakisfil** [w3c/push-api#119]
Hi! I am not sure if this is the correct channel to ask my question. Are there any current implementations for this API ? Where should I look to track future implementations ?

**Comment by mvano** [comment]
Chrome is shipping its first implementation in M42: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/UdGlL9PtBLo/HOZZ4sjV-QkJ

We plan to iterate on this implementation, based on the known issues, and developer feedback.

Note that the Push API was derived from Mozilla's Simple Push, which shipped some time ago in installed apps on Firefox OS. Afaik Mozilla is currently working on implementing the Push API in Firefox for all platforms.

**Comment by vasilakisfil** [comment]
Thanks! You can add the link on the Readme.
