### ISSUE TITLE
pushsubscriptionchange - Initial feedback

### ISSUE THREAD

**Issue by gauntface** [w3c/push-api#120]
After talking with @johnmellor and @jeffposnick on different occasions a few concerns have come up that may be worth discussing the appropriate approach from a developer approach or see if the API simply is the best approach.
- It feels like the pushsubscriptionchange event results in a somewhat poor experience for the user if there is any kind of error. If the subscription changes, the developer re-subscribes (assuming the permission state has changed), tries to send this to their server, that fails for whatever reason, now the developer has no way out other than to wait for the user to visit their page again in the hope that they can then send the new subscription.
- @jeffposnick had some concerns with respect to performing an update of the subscriptionId and endpoint when OAuth is needed to authenticate the user.

I understand that in Chromes current implementation this isn't a problem since GCM doesn't have a need to change the subscriptionId (at least to the best of my knowledge), but for future implementors, this feels like the API will result in a number of bad patterns by developers or poor experiences for users (i.e. randomly opening windows to update the subscription details OR the user simply not getting the push messages because the subscription could be updated on the server).

Is it worth considering moving this to something that can only occur when the user is on the web page?

**Comment by martinthomson** [comment]
I think that the primary concern here is the window of time between when a subscription expires or breaks and the application server is updated with new details.  A lot happens in that time potentially.

On the positive side, a lot of that can be masked by the browser, at least for expiration.  The browser can continue to maintain the old subscription until the event it delivers to the SW has been resolved (that is, if `e.waitUntil()` is used properly).  In the case of a break, the outage window is unavoidable.

There is no need to open windows, though. That would simply be bad design.  Just `fetch()` the new details to the server (ugh, that's an awkward turn of phrase).

I think that perhaps the above should be made part of the algorithm for delivering `pushsubscriptionchange` events.

p.s., I believe that GCM does change identifiers in rare occasions (i.e., if a node crashes, but I guess that would happen very rarely).

**Comment by gauntface** [comment]
I think you have pointed out the main detail I've failed to spot, if the
event.waitUntil fails to resolve then the old subscriptionId would remain
unable.

**Comment by beverloo** [comment]
PR #234 defined this in a new `Subscription Refreshes` section. We suggest using background sync for getting the updated details to your server (which has yet to be changed), and don't _require_ the old subscription to be immediately invalidated exactly to allow for a brief window during which the change can propagate.
