### ISSUE TITLE
Remove [NoInterfaceObject] from PushMessageData 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/push-api#123]
Please stop using [NoInterfaceObject]. It's bad for extensibility. For instance, if we I want to polyfill a new processing method on `PushMessageData` (i.e., .fancyMsgFormat()), I won't be able to do that without it being a huge pain the ass.

**Comment by beverloo** [comment]
Yes please.

+@johnmellor who was against this.

**Comment by mounirlamouri** [comment]
:+1:
