### ISSUE TITLE
userVisible -> userVisibleOnly

### ISSUE THREAD

**Issue by beverloo** [w3c/push-api#137]
In #131 I introduce the `userVisible` option to the `PushSubscriptionOptions` dictionary. We've since received [some feedback](https://groups.google.com/a/chromium.org/d/msg/blink-dev/_2JV9BTB1Ec/33xzm_MTzVYJ) that `userVisibleOnly` is considered to be clearer.

I'm OK with this change, and don't feel strongly in either direction. The reasoning for going with `userVisible` initially is that UAs could provide some _grace_ for pages that miss a notification or two, but are otherwise good players.

However, the intention declared by the developer says that the subscription will **only** be used for messages that result in user visible UI.

**Comment by mvano** [comment]
FYI, the corresponding property in the Permissions API is also called userVisible: https://w3c.github.io/permissions/#push

If we change it in the Push API, we should also change it in the Permissions API for consistency.

Independently from the consistency issue, I feel that `userVisibleOnly` is quite verbose and the `Only` part does not add enough value to warrant such verbosity. Just `userVisible` seems equally clear.

**Comment by beverloo** [comment]
Could we define the PushPermissionDescriptor in our API?

**Comment by mvano** [comment]
Could we? I was wondering about the expectations around updating the Permissions API as needed.

**Comment by mvano** [comment]
It would introduce a formal dependency on the Permissions API though.

**Comment by beverloo** [comment]
That seems fine to me.

Also note that it's not so much a dependency (though we'll have to add a normative reference), we'd extend it.

+@mounirlamouri @marcoscaceres

**Comment by johnmellor** [comment]
+1 for userVisibleOnly. Otherwise it's confusing, since userVisible:false incorrectly implies that notifications will never be shown, when actually false is simply more flexible - it means notifications may or may not be shown.

**Comment by mvano** [comment]
Looks like we have consensus for `userVisibleOnly`, John's argument makes sense.

**Comment by beverloo** [comment]
@martinthomson Just to confirm - no concerns about this rename?

**Comment by martinthomson** [comment]
Gecko doesn't plan to use this, so whatever you call it has no real impact on what we do :)
