### ISSUE TITLE
Should receipt_endpoint be expose in PushSubscription of webpush api

### ISSUE THREAD

**Issue by ddragana** [w3c/push-api#144]
PushSubsctiption has two parameter: endpoint and subscriptionId.

Webpush ietf draft have an additional parameter Receipt Endpoint. If it does not change, ReceiptEndpoint should be added.

**Comment by beverloo** [comment]
This was resolved a few days ago by #129 - we now only define "endpoint". You can see this in the latest version of the spec here:

https://w3c.github.io/push-api/#pushsubscription-interface

**Comment by martinthomson** [comment]
@beverloo,

I think that the point @ddragana makes is that the proposed protocol has another endpoint that the application can use to request delivery receipts.

I was going to propose something, but wait for the discussion around acknowledgments to mature a little more.  Until then, given that `pushReceiptSubscriptionEndpoint` is too much of a mouthful, we could use an experimental name of `receipts`.

**Comment by martinthomson** [comment]
With changes to the protocol, this is no longer needed.
