### ISSUE TITLE
Push event shouldn't be dispatched to an activating worker

### ISSUE THREAD

**Issue by mfalken** [w3c/push-api#147]
The current spec will deliver a push event to the "active worker". However, this worker may have status "activating" rather than "activated". The SW spec intends for "activating" workers to not receive functional events yet (https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#service-worker-state), so Push spec probably should also do the same.

**Comment by annevk** [comment]
Really Push should leave it up to the SW spec to find a worker and dispatch an event to it. Otherwise each new API will need to go through the same exercise.

**Comment by martinthomson** [comment]
I think that if we fix #146, we'll fix this as well.

**Comment by martinthomson** [comment]
Yes, #146 is fixed (though not by this).
