### ISSUE TITLE
pushregistrationlost isn't documented

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#149]
We keep talking about this, and I think we still need it.  The `pushsubscriptionchange` event is fine for the case where the browser is able to seamlessly switch out the current subscription for another.  However, there are plenty of cases where the subscription

We could use `pushsubscriptionchange` and then return _null_ out of `getSubscription()`, but that seems janky.

This relates to #116 and #61.

**Comment by martinthomson** [comment]
Oh yeah, and using `pushsubscriptionchange` (damn that's a handful to type), we don't get to learn whether the browser is automatically retrying a connection, or whether we're expected to ask again.  `pushregistrationlost` (which might be better as `pushsubscriptionlost`) would allow us to say that this is a terminal condition and the SW is responsible for asking to renew the subscription.

**Comment by mvano** [comment]
These all look like rejected naming variations for the same event, we settled on the `pushsubscriptionchange` name after quite a lot of discussion. I'm not sure what question you are asking here, could you clarify?

**Comment by martinthomson** [comment]
Let us at least decide whether `pushsubscriptionchange` is sufficient.  `change` is great if you can get a replacement, but it seems deficient when you have an outright error.

**Comment by mvano** [comment]
What use case do you have in mind? How does the current recommendation to attempt to resubscribe not apply for this new use case?

**Comment by martinthomson** [comment]
OK, I can see now where the confusion arises. We need to be a lot clearer about error conditions, but this is the wrong place for that, I'll open another ticket.

**Comment by karlcow** [comment]
> OK, I can see now where the confusion arises. We need to be a lot clearer about error conditions, but this is the wrong place for that, I'll open another ticket.

@martinthomson did you open this other ticket?

**Comment by martinthomson** [comment]
@karlcow I have no idea.  This was quite a long time ago.
