### ISSUE TITLE
How to implement the retry send notification if the confirmation for notification send is missing in API documentation

### ISSUE THREAD

**Issue by cashinde** [w3c/push-api#151]

**Comment by beverloo** [comment]
Your question seems to be about re-sending an important push message from your application server when the push service does not give you a successful delivery receipt for the first attempt. Is that correct?

When vendors start using the Web Push protocol, you can request a receipt by adding the Push-Receipt header to your initial message. This will then be delivered to you as described in the protocol[1].

Until that, you should refer to the documentation of the push service you are currently using. For example, see this guide and the associated reference for GCM.

```
https://developers.google.com/cloud-messaging/server
```

[1] http://www.ietf.org/id/draft-thomson-webpush-protocol-00.txt
