### ISSUE TITLE
Binary messages and use of `USVString` in `PushMessageDataInit`

### ISSUE THREAD

**Issue by ghost** [w3c/push-api#159]
Section 10 states "`PushMessageData` objects have an associated bytes (a byte sequence) set on creation." Given that—and the `blob()` and `arrayBuffer()` methods—I'm curious why `PushMessageDataInit` uses `USVString` instead of, e.g., `ArrayBuffer`. Does this mean that all decrypted messages must be UTF-8 encoded strings?

**Comment by martinthomson** [comment]
I think that this is just in error.  The source here should be a sequence of bytes, because that is what comes in across the wire (even in a protocol that only carries strings, this reduction is possible).  Then, the string variants of the mixin can decode that string using whatever hints available from the underlying protocol, like `charset` parameters.  That might fail.

**Comment by annevk** [comment]
No, we should not support `charset` parameters. If you get a string it should only be from utf-8 bytes. (Bytes decoded as utf-8, with replacement as error handling mode.)

**Comment by ghost** [comment]
> If you get a string it should only be from utf-8 bytes. (Bytes decoded as utf-8, with replacement as error handling mode.)

Should we decode when creating the `PushMessageData` object, though, or only when `text()` is called? I'm guessing the latter, since we expose `blob()` and `arrayBuffer()`, and UTF-8 decoding will garble binary messages. Section 11.1 seems to imply this:

> - Let `event` be a new `PushEvent`, whose data attribute is a new `PushMessageData` with `bytes` set to the binary message data received by the user agent in the push message, or an empty byte sequence if no data was received.

So `bytes` is a byte sequence, but `PushMessageDataInit` is a `USVString`. Would it make sense to have something like this instead?

``` webidl
typedef sequence<octet> PushMessageDataInit;
```

**Comment by annevk** [comment]
Only when `text()` is invoked, yes.

**Comment by annevk** [comment]
I think `PushMessageDataInit` only accepts a string for now to keep things simple. That string does need to be utf-8 encoded of course...

**Comment by martinthomson** [comment]
Strings aren't encoded...  Though yes, I'm OK with limiting the supported encodings to UTF-8 (that keeps things simple, as well as preventing charset use from being encouraged).

I have no problem accepting a string (probably `DOMString`) for `PushMessageDataInit`, though we would require that it first be encoded using UTF-8 before continuing.

**Comment by annevk** [comment]
I meant that the input string needs to be utf-8 encoded before you have your bytes that `PushMessageData` needs... Which seems to be exactly what you're saying too in your last paragraph.
