### ISSUE TITLE
What push daily sending limit have GCM from single account?

### ISSUE THREAD

**Issue by dzmrf** [w3c/push-api#163]
Hi
Have someone information about critical GCM sending limit?
For example if i'll generate GCM Api key and use it for 100 websites and will sent 100K pushes dayli it will be posiible?

**Comment by miguelgarciaarribas** [comment]
We'd prefer to avoid discussing GCM specific questions here and keep this github project for the spec itself. Feel free to post to https://groups.google.com/forum/#!forum/android-gcm. Your question is very relevant and we'll be happy to answer there.

**Comment by dzmrf** [comment]
thanks
