### ISSUE TITLE
Mark `PushMessageData` methods as throwable

### ISSUE THREAD

**Issue by ghost** [w3c/push-api#165]
`arrayBuffer()`, `blob()`, and `json()` can throw due to, e.g., memory allocation failures or invalid JSON.

**Comment by martinthomson** [comment]
`text()` can throw too - it needs to be a valid `USVString`.

**Comment by martinthomson** [comment]
Of course, anything in WebIDL can throw.  `[Throws]` is a Mozilla-specific WebIDL construct.
