### ISSUE TITLE
Multiple consecutive messages

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#168]
If an application has a bunch of inbound messages, there is no way for it to know whether subsequent and imminent push messages could invalidate that message.  This can result in poor user experience.

The canonical example is where a user is offline with one device but online on another.  The offline device will receive a message for an event, the online device might acknowledge the event, which causes the offline device to receive another message that cancels the first.

However, when the offline device comes online, the first message is delivered first, without context.  Now, we could recommend that the server uses a protocol collapse mechanism (see https://github.com/webpush-wg/webpush-protocol/pull/12).  However, there are still race conditions where this still produces poor UX.  And it doesn't deal with the case where there are multiple messages, all of which you want, that you want to treat collectively in a different fashion as a result of having multiple.

I think that we should consider adding a method to `PushManager` so that applications can peek into the future to avoid this sort of problem.

**Comment by beverloo** [comment]
In Chrome we fire the `onpush` events in parallel, so especially in a world where additional network access is necessary to fetch the _why_ of a push, all of the messages that would be in the queue will already been executing.

Without understanding the impact of having payloads, I'm a bit hesitant for us to deliver incoming messages sequentially. It could significantly increase the time the UA is active, increasing the chance of failed message deliveries because of external conditions (e.g. memory conditions).

In practice, we haven't seen issues with this either. When wouldn't supporting message collapsing on the push service address this problem? https://github.com/webpush-wg/webpush-protocol/issues/9

**Comment by martinthomson** [comment]
I don't think that it can ever truly be parallel.  After all, Javascript is run-to-completion.  I'm not suggesting that we let the waitUntil promise on the first run, just that in the synchronous processing you have no opportunity to learn of what comes next.

Even if multiple events will be delivered into the event loop at the same time, you can't do anything to learn about what is pending until you complete the synchronous (and Promise-based) processing of the first event.

You can't even collect messages by adding a callback to the end of the event loop without some pretty ugly haxx. Promises only generate microtasks and get executed ahead of the next event in the loop. Fetch or some other asynchronous API might work for that purpose, though I'm not sure that postMessage to self works due to various optimizations that are used.

I don't think that forcing sites to use hacks here is the right answer.

Collapsing only helps in the case that the messages are not able to be delivered.  Once the message has been delivered to the next stage of the pipeline, it can't be recalled.

**Comment by beverloo** [comment]
What you describe as "next stage of the pipeline" means "has been received by the UA". In context of the two-device example where collapsing cannot be used, this means that the case in which this would happen is:
1. **AS**: Sends "you've got mail" announcement to UA1 and UA2.
2. **UA1**: Announcement received, event queued up and dispatched.
3. **UA1**: Announcement acknowledged by user, informs app server.
4. **UA2**: _[comes online]_ Announcement received, event queued up, _not_ dispatched yet.
5. **AS**: Sends "ignore that message" cancelation to UA2.
6. **UA2**: Cancelation received, event queued up, dispatches both events in order.

The race happens between step {4, 5} and 6 - the order of 4 and 5 can be reversed when we account for the latency between the AS, the PS and the UA.

The synchronous part of invoking the `push` event is run-to-completion, any other operation the developer would do is very likely to be asynchronous. Firing subsequent events happens sequentially, they are not blocked on the previous one _finishing_ (accounting for `waitUntil`) - this is what I meant by running in parallel.

If we assume all events have been added to the task queue before any of the events run, you're proposing to add a mechanism to peek into the task queue and grant access to any queued `push` events, including their data. The mechanism would only provide value during the synchronous part of the event, as the queue would have been flushed by the time any Promise settles.

This introduces a lot of complexity, and introduces a concept (peeking into the task queue) that, to my knowledge, does not exist in the Web platform yet. It also makes the assumption that the UA is able to queue up all pending events before tasks in the task queue are being executed - this may not always be the case.

I'm not at all convinced that the added complexity is worth it. The chance of this happening, when message collapsing is appropriately used (not informing the UA in the first place is highly preferred), is very theoretical. Have you seen this in practice?

**Comment by martinthomson** [comment]
Discussed with @beverloo.  We have never had anyone complain about this.  And it seems really hard to fix, unless you do something stupid, like expose a list.  Which would be flakey.

Closing.
