### ISSUE TITLE
PushMessageData.arrayBuffer() should throw a RangeError when allocation fails

### ISSUE THREAD

**Issue by junov-google** [w3c/push-api#169]
The ECMAScript specification states that array buffer allocation failures throw a RangeError exception.
The spec for PushMessageData.arrayBuffer() should probably state that it re-throws exceptions that are thrown by arrayBuffer creation.

**Comment by junov-google** [comment]
For reference: http://ecma-international.org/ecma-262/6.0/#sec-createbytedatablock

**Comment by martinthomson** [comment]
Care to produce a pull request for that @junov-google ?

**Comment by junov-google** [comment]
Sure. But bare with me, I am new to GitHub

**Comment by martinthomson** [comment]
Closed in #170
