### ISSUE TITLE
Can you change the value of PushSubscriptionOptions

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#183]
When calling `subscribe()`, what happens if there is an active subscription with a different set of values for its `PushSubscriptionOptions`?  We can reject the call with `InvalidAccessError`,  `NoModificationAllowedError`, or even `InvalidStateError`.  Or we can create a new subscription with the new options.

I think that the current view is that rejection is cleanest (and leads to fewer surprises).  However, in the we will need to separately expose the current state of the options in the interests of transparency. 

This came up in #182.

**Comment by mvano** [comment]
I slightly prefer <code>InvalidStateError</code>, as <code>NoModificationAllowedError</code> ties us closer to the one subscription per registration model.

There is a very small chance that this would break existing functionality. But really currently it's only the <code>userVisibleOnly</code> boolean so maybe it's best that we change this behavior before the really interesting stuff is added to <code>PushSubscriptionOptions</code>.

**Comment by martinthomson** [comment]
This was addressed in #187.
