### ISSUE TITLE
typedef object JSON; is incorrect

### ISSUE THREAD

**Issue by domenic** [w3c/push-api#204]
`"foo"`, `5`, and `null` are all valid JSON.

Better to just use `object` when you mean `object`.

**Comment by beverloo** [comment]
We don't mean `object`, we mean JSON— the payload will be passed through `JSON.parse`.

What would you suggest we use instead? `any`?

**Comment by domenic** [comment]
Yeah, that would work better.

**Comment by beverloo** [comment]
Cool, will fix in the morning :) Thanks for the note!

**Comment by annevk** [comment]
Note that Fetch also defines JSON. We cannot really define it twice. Perhaps we should both give up and just say "any" and remove the typedef?

**Comment by domenic** [comment]
We could also move it to Web IDL.

**Comment by annevk** [comment]
Seems okay, if there's value in having it.

**Comment by domenic** [comment]
Yeah, I'm not entirely convinced there is. If we were to do something in Web IDL that was JSON related, I'd think it would abstract away the JSON.stringify work and maybe convert it into bytes for you or something.

**Comment by annevk** [comment]
This is more like the opposite. If we could hand IDL bytes, and it would utf-8 encode those and then turn them into a "JSON object", that would actually have some benefits.

**Comment by annevk** [comment]
But still minor, of course.

**Comment by annevk** [comment]
I don't think that solves the duplication issue. Any thoughts on that @mvano?

**Comment by mvano** [comment]
@annevk : It seems it's duplication of a one-line typedef, which at this point is basically just there to improve readability. It looks ok to me, but I'm not attached to it, we could just as well delete it if it causes confusion.

**Comment by annevk** [comment]
I'm leaning in the direction of removal for Fetch. Perhaps if we can introduce JSON-specific syntax in IDL it's worth it, but that's probably not worth the hassle either.

**Comment by annevk** [comment]
Done.
