### ISSUE TITLE
applicationServerKey is never used in subscribe()

### ISSUE THREAD

**Issue by jyasskin** [w3c/push-api#209]
[PushManager.subscribe()](https://w3c.github.io/push-api/#widl-PushManager-subscribe-Promise-PushSubscription--PushSubscriptionOptionsInit-options) checks `applicationServerKey` for validity, but it never actually uses the value.

**Comment by martinthomson** [comment]
That is correct, the browser doesn't actually use this value.  It should send this to the push service though.  We should fix that.
