### ISSUE TITLE
pushManager.subscribe()  use google's Firebase Cloud Messaging (FCM) API in Chrome

### ISSUE THREAD

**Issue by itchina110** [w3c/push-api#213]
```
navigator.serviceWorker.register('serviceworker.js').then(
  function(serviceWorkerRegistration) {
    serviceWorkerRegistration.pushManager.subscribe().then(
      function(pushSubscription) {
        console.log(pushSubscription.endpoint);
        console.log(pushSubscription.getKey('p256dh'));
        console.log(pushSubscription.getKey('auth'));
        // The push subscription details needed by the application
        // server are now available, and can be sent to it using,
        // for example, an XMLHttpRequest.
      }, function(error) {
        // During development it often helps to log errors to the
        // console. In a production environment it might make sense to
        // also report information about errors back to the
        // application server.
        console.log(error);
      }
    );
  });
```

**Comment by martinthomson** [comment]
I can't interpret this.  Can you try to summarize the issue?

**Comment by itchina110** [comment]
@martinthomson In Chrome, PushSubscription.endpoint's value is "https://android.googleapis.com/gcm/send/...", I hope this is my own server to return.

**Comment by martinthomson** [comment]
Not sure that I understand your concern.  You use the value of `endpoint` with the protocol described here: https://tools.ietf.org/html/draft-ietf-webpush-protocol-12

**Comment by itchina110** [comment]
In Chrome, the pushManager.subscribe() method requests Google's proprietary service by default, I can't get any chance to modify the server to, for example, my own server that has implemented the Web Push Protocol, although the W3C's Push API does defined two parameters for the pushManager.subscribe() method.

**Comment by martinthomson** [comment]
I suggest that you contact the chrome developers.  This isn't an issue with the specification, which allows browsers to make their own choices about push service.  Google's choice to use Google's proprietary service is something that I suspect will not change.  Of course, chromium is open source, so I guess anything is possible if you are sufficiently motivated.

Good to hear that someone is implementing the protocol though.  I hope that some day there will be an option to use a personal push server in Firefox, but we too have our own proprietary protocol right now.

**Comment by beverloo** [comment]
I think that there are two misunderstandings here—
1. The Push API explicitly does not allow for the _bring your own push service_ scenario. Which part of the specification gave you the impression that this was possible?
2. Calling `pushManager.subscribe()` will in fact return a Web Push Protocol-enabled version in Chrome.

You can, of course, do whatever you want if you decide to fork any open source browser that supports the API.
