### ISSUE TITLE
Properly defining `pushsubscriptionchange`

### ISSUE THREAD

**Issue by beverloo** [w3c/push-api#228]
Hi all —

The `pushsubscriptionchange` event ([ref](https://w3c.github.io/push-api/)) is rather poorly defined right now. There are several issues requesting changes and clarifications. I'd like to propose the following semantics for the event.

There are three scenarios in which the browser may want to fire the event.

1. **Subscription invalidation**. This happens when any property of the subscription changes: a new endpoint (expiration and/or refresh) or new encryption keys. The UA should resubscribe on behalf of the developer _before_ firing the event. The old subscription should continue to work until either the new subscription has been used, or a certain period of time passes, e.g. 90 days.
2. **Subscription revocation**. This happens when the UA has dropped the subscription: permission got revoked (#116) or suspended because the website ran out of quota. The website cannot resubscribe in this case.
3. **Subscription lost**. This happens in situations where the UA loses the subscription: database corruption on the PS, or partially on the UA. The UA should attempt to resubscribe on behalf of the developer _before_ firing the event.

Clearing data (#61) is explicitly excluded from scenario (2). We should not inform websites when that happens, even though the application server can still detect this as the push service should reject new messages if/when the unsubscription has propagated. I consider Firefox' invocation when permission is regranted to be equivalent to scenario (3).

I think that we can support these scenarios with the following interface (#132).

The `oldSubscription` attribute (#193) would be NULL in the _subscription lost_ scenario when it's known that there was a subscription, but no complete `PushSubscription` object could be created.

The `newSubscription` attribute would be NULL in the _subscription revocation_ case, as well as in the _subscription lost_ case when resubscribing fails due to insufficient knowledge (i.e. `applicationServerKey`) or networking errors.

```webidl
interface PushSubscriptionChangeEvent : ExtendableEvent {
    readonly attribute PushSubscription? newSubscription;
    readonly attribute PushSubscription? oldSubscription;
};
```

We'll advocate use of [Background Sync](https://wicg.github.io/BackgroundSync/spec/) (#120) for transferring the updated subscription information to the server. This enables us to deal with failed fetches without effectively duplicating that entire specification. Note that Background Sync currently does not support this use-case due to restrictions: it requires a top-level frame in order to register. We'll propose changing the spec.

On a tangent, two changes I'd like to make in Chrome to help developers are (a) issuing a console warning when there's a listener for the `push` event, but not the `pushsubscriptionchange` event, and (b) adding a button to DevTools for manually triggering a `pushsubscriptionchange` event.

Before I go off and update the spec, I'd love your feedback on this :).

/cc @martinthomson @kitcambridge @gauntface @ShijunS

**Comment by martinthomson** [comment]
Subscription invalidation - I think that once an application has responded to the event (and all the waitUntil promises have resolved), the UA should be free to release the old subscription.  Otherwise, I think that this is great.

**Comment by johnmellor** [comment]
Resolving the waitUntil promise doesn't guarantee that the web server sending pushes has been updated (e.g. on a flaky network). Guaranteeing that would require retrying delivery of the pushsubscriptionchange, which gets messy and duplicates Background Sync.

**Comment by ShijunS** [comment]
A couple comments:

From the proposed API, apps won't be able to tell why the event was triggered.  When the "newSubscription" is null, the apps might attempt to request for a new subscription again.  In case a user revokes the permission or the UA revokes the subscription due to violation of the userVisibleOnly setting, it might not be desirable for the user to see a user permission prompt right away.  It'd be nice to at least include a note to recommend checking the permissionState.  Meanwhile, the UA should have some flexibility in firing the event in scenario (2).  For example, clearing notification permissions for all sites is fairly close to clearing browsing history from the user experience perspective. 

In addition, Re scenario (1), should the event also be fired when the oldSubscription actually expires, maybe with oldSubscription set to "null"?

**Comment by ghost** [comment]
This looks terrific. Passing both `oldSubscription` and `newSubscription` is nice, and avoids having the worker make an extra `subscribe()` call to get a new endpoint, or figure out if it still has permission.

Making `oldSubscription` nullable seems a little strange: the browser knows the service worker had a subscription, but can't construct a full `PushSubscription` object? The browser could resubscribe and pass `newSubscription`, but that might not be useful to the app server if it depends on knowing the old endpoint. Could we treat this similarly to #61 and not fire `pushsubscriptionchange`?

For invalidation, I agree with @johnmellor. `waitUntil` doesn't offer enough guarantees that the new subscription info made it to the app server. Using the subscription for the first time is pretty clear.

**Comment by beverloo** [comment]
@ShijunS 

> In case a user revokes the permission or the UA revokes the subscription due to violation of the userVisibleOnly setting, it might not be desirable for the user to see a user permission prompt right away.

This is interesting - to my knowledge, currently no browser enables websites to request permission from a Service Worker. Without having a visible foreground tab, how does the user get sufficient context to make a decision?

My thinking with including the `newSubscription` in the event is that it avoids developers from having to call `subscribe()` at all. If they _can_ resubscribe, the UA will already have done so on their behalf.

> Meanwhile, the UA should have some flexibility in firing the event in scenario (2). For example, clearing notification permissions for all sites is fairly close to clearing browsing history from the user experience perspective.

Would it work for you if I phrase the permission revocation scenario with `SHOULD` as opposed to `MUST`? I can see what this may be hard to support architecturally.

I make the assumption that the UA will remove the subscription when permission is revoked, which means that the push service will start rejecting new messages anyway. (Thereby making it observable by the developer.)

> In addition, Re scenario (1), should the event also be fired when the oldSubscription actually expires, maybe with oldSubscription set to "null"?

Since the user agent at least needs to replace the old subscription with the new one, we know there to be an association so presumably it could just read the data of the old subscription prior to removing it?

Some applications store settings and data keyed by the subscription's endpoint to avoid requiring users to log in. It's important for them to be able to migrate such data from the old subscription to the next.

@kitcambridge 

> Making oldSubscription nullable seems a little strange: the browser knows the service worker had a subscription, but can't construct a full PushSubscription object?

Your experiences would actually be really interesting here, actually.

We're seeing two cases in which this is relevant. _(1)_ The UA hasn't connected to the Push Service at all in >9 months, so we _forgot_ about them, and _(2)_ we see a non-negligible amount of file I/O-related database corruptions in the client of our Push Service.

In both cases we know that there used to be a subscription that won't work anymore. In the first case we can provide full data, but in the second case we may only have partial subscription information (usually missing the keys) and the Push Service won't be able to tell the AS that the subscription's gone either.

Admittedly it's an edge-case. If you don't see anything like this right now, I could certainly be convinced to drop it. My thinking here was that the transition from nullable to not-nullable usually is easier than the other way around.

**Comment by ghost** [comment]
@beverloo

> We're seeing two cases in which this is relevant. (1) The UA hasn't connected to the Push Service at all in >9 months, so we forgot about them, and (2) we see a non-negligible amount of file I/O-related database corruptions in the client of our Push Service.

We've seen both cases, too. For case (1), our server is a lot more aggressive; it'll drop all subscriptions for a UA if it hasn't connected in 60 days. Those are stored locally, so we'll have full data.

Case (2) is fun. Our subscription storage mechanism is based on IndexedDB, and it's possible to induce corruption by switching between older and newer versions with the same user profile. Unfortunately, that breaks Push entirely (https://bugzilla.mozilla.org/show_bug.cgi?id=1258596): we can't retrieve subscription information at all.

We'd like to make this more robust in Firefox, so I can definitely see a case where we might be able to extract partial info. Considering your point that it's harder to make things non-nullable later, I'm totally OK with leaving it nullable.

> The `newSubscription` attribute would be NULL in the subscription revocation case, as well as in the subscription lost case when resubscribing fails due to insufficient knowledge (i.e. `applicationServerKey`) or networking errors.

After thinking about this a bit, I have a couple of questions. If the subscription has an `applicationServerKey`, is the browser allowed to resubscribe using that key? This would work if the browser stored the entire key (which Firefox does, to check if you're calling `subscribe()` with a different `applicationServerKey`), but not if it only stored a fingerprint. Or should we always leave it up to the service worker to resubscribe if the old subscription had an `applicationServerKey`?

For network errors: I assume the browser is allowed to retry if resubscribe fails, and only fire `pushsubscriptionchange` with `newSubscription` set to `null` if it exceeded the maximum number of retries, or if the server is permanently offline?

**Comment by gauntface** [comment]
Overall I'm +1 your proposal.

Assuming that the newSubscription would also be the result of calling `pushManager.subscribe(options)` then the approach I would expect most developers to take is to attempt subscribe the user, regardless of permission state or `event.newSubscription`, sending the result to their application server or catching the error. At the same time removing the old subscription from the backend by either using event.oldSubscription or their own indexeddb result.

**Comment by ShijunS** [comment]
@beverloo 

> Would it work for you if I phrase the permission revocation scenario with SHOULD as opposed to MUST? I can see what this may be hard to support architecturally.

Yes, that would certain help from implementation perspective so the UA can have flexibility in handling corner cases.

> Since the user agent at least needs to replace the old subscription with the new one, we know there to be an association so presumably it could just read the data of the old subscription prior to removing it?

Good point.  It is certainly doable that way.  Meanwhile, would it be useful to allow the app to distinguish between two cases (a) when the old subscription is still valid, and (b) when the old subscription is invalid already?

**Comment by martinthomson** [comment]
I think that any time you get this event, it will be because the UA wants you to stop using the old subscription.  Whether it's already dead or only imminent, any signal that might be used to extend the life of the old subscription will make it harder to remove it properly.

I'm already sad about the fact that this event might not be the end for the old subscription.

**Comment by ShijunS** [comment]
That is a fair statement.  So, to the apps, there is no guarantee that the old subscription is still valid when receiving the event.  It is almost equivalent to indicating the end of the old subscription.  I agree it is better then not to distinguish the two cases I mentioned.
