### ISSUE TITLE
Propose enabling background sync from `pushsubscriptionchange` events

### ISSUE THREAD

**Issue by beverloo** [w3c/push-api#240]
We advocate use of it, so we need to make sure it works. I'll file an issue.

**Comment by martinthomson** [comment]
@beverloo, can you mention the issue when you do so so we can see its status from here?

**Comment by NekR** [comment]
So it doesn't in browsers (Firefox?) right now? Also, what about registering Background Sync from `push` event?

**Comment by ghost** [comment]
Firefox doesn't implement background sync yet, but you can follow [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1217544) if you'd like. IIUC, step 6 in the [`SyncManager.register` algorithm](https://wicg.github.io/BackgroundSync/spec/#sync-manager-interface) means you can't register a background sync from either handler when the page isn't active. That restriction can be lifted, though, and a `push` event might be a good opportunity to show a notification and schedule a sync for a later time.

**Comment by NekR** [comment]
@kitcambridge Makes sense, thank you!

**Comment by marcoscaceres** [comment]
Marking as V2, as background sync is still not a widely supported thing.

**Comment by marcoscaceres** [comment]
Closing as out of scope for now.
