### ISSUE TITLE
Who will provide the Push Service?

### ISSUE THREAD

**Issue by VenyXiong** [w3c/push-api#247]
The GCM/FCM is apllied to Both Chrome and Andriod. 
So I'm a little confused about that who will provide the Push Servive ? The Browser vendors or the Operating system vendors？
Thanks for the answer~

**Comment by beverloo** [comment]
Hi @VenyXiong,

Implementations should use what's best for the user, while meeting the requirements of the standards. That means that if the operating system provides a push service that's fit for use with Web Push, it would be advisable for the browser to use it.

Specific to Chrome, we use the FCM client provided by the operating system on Android, and ship our own push service client (for FCM) elsewhere. I would like us to use WNS/APNS when the user's operating system is modern enough, but that requires quite a large amount of work.

I hope this clarifies things!
