### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/push-api#261]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by beverloo** [comment]
It doesn't look like there's an interest. I'm not currently planning to attend, but can change that if someone else feels strongly.

/cc @martinthomson @ShijunS

**Comment by martinthomson** [comment]
I don't plan to attend either.  The open issues we have are progressing well enough on github.

**Comment by LJWatson** [comment]
Thanks for letting me know.
