### ISSUE TITLE
Meta: wide-review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/push-api#265]
A11y: [complete](https://www.w3.org/WAI/APA/wiki/Push_API)
Issue #259 (closed)

I18n: [complete](https://github.com/w3c/i18n-activity/issues/406)
Issues #276 (closed) and #275 (closed)  

Privacy: completed.

Security: [complete](https://lists.w3.org/Archives/Public/public-web-security/2017Jun/0003.html)
Issues #273 (closed) and #270 (closed) 

TAG: [complete (with comments)](https://github.com/w3ctag/design-reviews/issues/184)

**Comment by LJWatson** [comment]
@Beverloo @martinthomson what is your sense of time needed to resolve these (and any other critical issues, before we're ready to transition to CR? Once in CR it'll be possible to make editorial updates to the spec, but all substantive issues/features etc. will need to be included in a future update.

**Comment by LJWatson** [comment]
Ping @beverloo @martinthomson

**Comment by martinthomson** [comment]
@LJWatson, I think that we're still waiting on the conclusion to #287.

**Comment by LJWatson** [comment]
Thanks @martinthomson.

We also need to look at #270 and #275. 

@beverloo, did you make the change arising from the Privacy review (" to clarify about UA deciding which push service to use.")? Thanks.

**Comment by LJWatson** [comment]
@martinthomson @beverloo loo it looks like #270 (from the security review) is still open, and that #287 is waiting for a response from one of you. Do you think we can get these wrapped up, so we can get the CR CFC out to the WG soon?

**Comment by LJWatson** [comment]
Ping?

**Comment by martinthomson** [comment]
Waiting on @beverloo.

**Comment by marcoscaceres** [comment]
Seems like everything got addressed.
