### ISSUE TITLE
Clarify that applicationServerKey can be required by implementations?

### ISSUE THREAD

**Issue by beverloo** [w3c/push-api#279]
Chrome requires developers to pass an `applicationServerKey`, Firefox does not. The specification considers it optional. Should we add a non-normative note about some implementations requiring this?

**Comment by martinthomson** [comment]
We didn't really consider the possibility (or at least I didn't) that it might be mandatory.  Since it could be, we need to define what happens if the value isn't there and the browser/push service require it.  That's more than a non-normative note.

**Comment by beverloo** [comment]
Good point, we'd have to upgrade the `subscribe()` algorithm as well. I guess it would be good for developers to know this prior to subscribing as well, but that could get a bit verbose. Let me send a PR for the `subscribe()` bits first.
