### ISSUE TITLE
Secure contexts

### ISSUE THREAD

**Issue by annevk** [w3c/push-api#282]
Any reason this is not using `[SecureContext]`? Would be good to add a note explaining why.

**Comment by beverloo** [comment]
The Push API predates `[SecureContext]`, so it's just an oversight.

I see that [`ServiceWorkerRegistration`](https://w3c.github.io/ServiceWorker/v1/#serviceworkerregistration-interface) is also marked as `[SecureContext]`, which is a dependency. Neither [Chromium's](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/serviceworkers/ServiceWorkerRegistration.idl?q=serviceworkerregistration&sq=package:chromium&dr=C&l=5) nor [Firefox'](https://github.com/mozilla/gecko-dev/blob/HEAD/dom/webidl/ServiceWorkerRegistration.webidl) implementations have been updated, so I wonder if they think it's safe to apply the change?

Semantically this should be `[SecureContext]`, we just have to make sure it's Web compatible. I'll figure out if we have a way of measuring this.

/cc @mattto @jakearchibald

**Comment by beverloo** [comment]
I filed https://github.com/heycam/webidl/issues/420 to figure out whether we should also specify this on the interfaces already limited to Service Workers, and thereby secure contexts. It's harmless to add those for now in either case.
