### ISSUE TITLE
Improve the sequence diagram

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#29]
I think the current sequence diagram in section 5 can be improved. Any ideas? I have a sample but not sure how to attach images to issues.

**Comment by mvano** [comment]
![image](https://cloud.githubusercontent.com/assets/5739872/4094029/7f879bcc-2fa3-11e4-8bb4-3391542ecad9.png)

**Comment by efullea** [comment]
It looks nicer than the current chart. I would though take the oportunity to highlight which steps are in the scope of this API (mainly the interactions between the 3 entities on the left), and which are just informative examples.

**Comment by mvano** [comment]
That's a good idea. How about this?

![image](https://cloud.githubusercontent.com/assets/5739872/4120295/35f35904-32b1-11e4-9d0c-30182c5a5d10.png)

**Comment by efullea** [comment]
Looks good to me. Another point, what is the criteria for solid / dotted lines? Do they respectively identify requests / reponses? It may be good to clarify.
