### ISSUE TITLE
Any overview of spec implementation status for browsers?

### ISSUE THREAD

**Issue by fatso83** [w3c/push-api#295]
I was wondering if there was any way of checking to what degree browsers conformed to the spec and/or this draft? 

A posting on SO regarding [whether the push service provider was configurable somehow](https://stackoverflow.com/questions/50326088/is-push-support-in-service-workers-dependent-on-internet-and-third-party-google) landed me on #287, #258 and #293, changing my perspective from "Not possible per the spec" to "This might well work, given support in the browser".

The problem now is finding out if and how the support is implemented. For instance, I read that [Firefox makes the service configurable](https://github.com/w3c/push-api/issues/258#issuecomment-309941959), but actually searching the net for info on this is rather fruitless, landing me on countless introduction articles. Some kind of feature table (with optional links to browser documentation) would be nice to have, but, of course, I do see this is outside the scope of this project. Still, you might know if such an overview exists?

**Comment by martinthomson** [comment]
This isn't really an appropriate place to ask questions.

https://developer.mozilla.org/en-US/docs/Web/API/Push_API is the best I'm aware of regarding documentation.  It's light.

https://caniuse.com/#feat=push-api is the usual place to go for feature compatibility information.
