### ISSUE TITLE
"handle functional event" no longer a thing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/push-api#315]
The spec previously linked to the Service Worker's concept of "handle functional event"... however, that was removed from the Service Worker spec at some point. 

@jakearchibald, could you provide us with some guidance on what we should link to now, or the right prose to use (if any)?

**Comment by jakearchibald** [comment]
Looks like this was broken in https://github.com/w3c/push-api/commit/31c671787201907d5db36e915071e3aba5508488. The correct wording was the previous wording, "Fire Functional Event".

https://w3c.github.io/ServiceWorker/#fire-functional-event-algorithm
