### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [w3c/push-api#337]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See heycam/webidl#2 for discussion.

**Comment by marcoscaceres** [comment]
It sets: 
https://w3c.github.io/push-api/#dfn-subscription-expiration-time

So, same as Geo. But we can probably just rename it or just use a unsigned long long.
