### ISSUE TITLE
Duplicate definition of PushPermissionDescriptor

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/push-api#343]
`PushPermissionDescriptor` is defined via an IDL fragment both in the Push API and in the [Permissions spec](https://w3c.github.io/permissions/#push). It should be defined in only one place.

cc @marcoscaceres

**Comment by marcoscaceres** [comment]
Yep, there is a PR to remove it from the Permissions spec. Just waiting on review. Should be fixed in 12 hours.
