### ISSUE TITLE
Mention Safari Implementation

### ISSUE THREAD

**Issue by karlcow** [w3c/push-api#362]
It's probably worth adding that Safari has an implementation of this specification.

https://github.com/w3c/push-api/blob/febe56bc064f1b86bde499c2e9d4d83da3a1a532/README.md?plain=1#L15C1-L20

**Comment by collimarco** [comment]
Yes, finally!

And this is the [full history](https://pushpad.xyz/blog/apple-is-working-on-web-push-notifications-for-safari/) of Web Push in Safari.
