### ISSUE TITLE
Provide support email for the major web push services

### ISSUE THREAD

**Issue by collimarco** [w3c/push-api#371]
Many Chrome (FCM) endpoints started to return 404 errors starting from 26 Jun. We did not change anything, so this is clearly a major bug or unannounced change in FCM.

The problem now is that there isn't a specific contact / email to discuss this major incident that is affecting millions of web push subscriptions.

1. **Can someone please share a contact / email of the Google team that is responsible for Chrome endpoints** (`https://fcm.googleapis.com/fcm/send/...`)?
2. Can we add a spec to the web push standard that requires to add a contact email to the responses (e.g. `X-Web-Push-Contact: team@push.example.com`)? Note that senders already include their email in the VAPID headers, so it would make sense to do the same on the other side.

**Comment by djswan** [comment]
I'll echo this concern. We're seeing the same thing over at Aimtell for millions of subscriptions.

**Comment by collimarco** [comment]
@djswan Thanks for confirming that you are also experiencing the same issue: I recommend to add your comment also to these related discussions [here](https://issues.chromium.org/issues/349646659) and [here](https://github.com/pushpad/web-push/issues/14).

In the meantime, if someone can provide a direct contact with FCM team that would be useful.

**Comment by welishr** [comment]
Hi reaching out from firebase please contact firebase support for issues: https://firebase.google.com/support/troubleshooter/contact. We can look into updating the standard to provide a support email, but our support team will be best equipped to help in situations where there are potential issues.

**Comment by saschanaz** [comment]
Indeed, while OP includes spec related issue too, please discuss Chrome or FCM issues in the corresponding support ticket rather than here.

**Comment by collimarco** [comment]
@welishr We contacted Google support using that form, but they don't even know what they are talking about. They are confusing the **proprietary FCM service and SDK for notifications** with the **Push API standard** supported by Chrome. They are refusing to help because we don't have a FCM project ID to inspect the issue. Obviously we don't have that... the Push API standard doesn't use it! 

Given that, can you please provide a direct contact (email or form) with the appropriate team?
