### ISSUE TITLE
Should push registration wait for Service Worker activation?

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#38]
If we expose `serviceWorkerRegistration.pushRegistrationManager.register` then it's possible to call it before the worker is activated. However, no push related events can be delivered before the worker is activated: not for receiving push messages, not for indicating the push registration was lost, etc. The event for push registration lost could never be fired if a worker is unregistered before it is activated. In that case, the app server would be holding on to expired push registration details.

So should push registration always fail before worker activation, to prevent this event delivery problem from occurring?

@jakearchibald @beverloo

**Comment by johnmellor** [comment]
See also slightlyoff/ServiceWorker#447, where @jakearchibald recommends making activate always succeed.

**Comment by mvano** [comment]
This was duplicated in the more recent and complete issue #92
