### ISSUE TITLE
unregister should return Promise<PushRegistration>

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#4]
The WebIDL signature should become:
Promise&lt;PushRegistration&gt; unregister ();

This way, the page does not need to store the registration on the client. When it unregisters, it can take the registrationId from the PushRegistration and send it to the app server. The app server can then drop it from storage and stop sending messages to it.

**Comment by mvano** [comment]
Maybe it should return only the registrationId, making the signature cleaner:
Promise&lt;DOMString&gt; unregister ();

**Comment by johnmellor** [comment]
Hmm, but pushRegistrationIds might not be globally unique, instead they might only be unique for a given pushEndpoint. So I guess web apps need to send both the pushEndpoint and the pushRegistrationId to their server?

**Comment by mvano** [comment]
Agreed with John, we should provide both.

**Comment by efullea** [comment]
Agreed that it is the pair of pushRegistrationId and pushEndpoint what is globally unique. About how both parameters are provided to the server it is a matter of the app server -> push server interface. (e.g. pushEndpoint may be the URL where to POST a notification, and pushRegistrationId a parameter of the request). 

Comment addressed in a new commit (https://github.com/efullea/push-api/commit/efe64099c76c7c7bc8775ba08f4fde8f66586b11) to #14
