### ISSUE TITLE
Is reliance on Web Push Protocol normative?

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#44]
The IETF Web Push Protocol (http://datatracker.ietf.org/wg/webpush/) is developed in collaboration with the Webapps WG to complement the Push API. It is not clear to me that it should at this time be a requirement for the push service underlying the Push API to support this protocol.

My suggestion: at this time, given the early stage of the Web Push Protocol development, I think it should be referenced in a non-normative section of the Push API spec.

@beverloo @martinthomson

**Comment by beverloo** [comment]
Given that the specification leaves space for different transport mechanisms (e.g. SMS) as well, and that the Web Push Protocol is still very much in flux and is thus likely to create more questions than answers, I agree with making this a non-normative reference for now. We can re-visit this prior to LC/PR.

In the future, if we choose to closely tie together encryption on the client and server sides, it would make a lot more sense to create normative references to either the Web Push Protocol, or, more likely, a RFC specific to the encryption solution.

**Comment by martinthomson** [comment]
I'd say that if the IETF choose to adopt something, that would be a more appropriate time to consider this one.
