### ISSUE TITLE
ServiceWorkerRegistration.pushRegistrationManager is very verbose

### ISSUE THREAD

**Issue by beverloo** [w3c/push-api#47]
Given the example in the specification:

```
navigator.serviceWorker.ready.then(function (serviceWorkerRegistration) {
  serviceWorkerRegistration.pushRegistrationManager.register(...);
});
```

This obviously is very verbose. We renamed "push" to "pushRegistrationManager" to avoid potential confusion with Array.prototype.push per a comment from the TAG.

A mid-ground would be to consider renaming this to "pushRegistration", as "manager" doesn't add any value in this case (there's only one active registration per SWR). However, there is a PushRegistration object as well, used by various methods on the PRM.

Straw man: Change the PushRegistration interface to be a dictionary instead. That way it doesn't have to be exposed on the global, and we can rename pushRegistrationManager to pushRegistration, avoiding developer confusion.

**Comment by jakearchibald** [comment]
`pushMessaging`, `pushManager`, `pushService`?

**Comment by mvano** [comment]
Using `pushManager` of type `PushManager` has worked well for me. It's how I implemented it in Chrome, and it has felt like a reasonably distinct identifier that is not overly verbose.

**Comment by johnmellor** [comment]
+1 for `pushMessaging` (nice and unambiguous)

**Comment by mvano** [comment]
I think all of Jake's suggestions are better than the current PushRegistrationManager. I'd prefer to avoid PushService because that's already a concept in the spec. I prefer PushManager over PushMessaging because it's a noun, so I went with that.
