### ISSUE TITLE
Clean up "webapp server" terminology

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#53]
We currently use a few variant terms for the same thing:
- Webapp server
- App server
- Application server

We should try to agree with the IETF Web Push Protocol WG on picking one and using only that one.

**Comment by beverloo** [comment]
I think "webapp server" is too narrow, given that the webapp may just be the front-end of a much larger application.

Since "app" is commonly used for client-side things, whether it be installable native apps or web apps, my preference has "application server".

**Comment by mvano** [comment]
See latest IETF draft: http://tools.ietf.org/html/draft-thomson-webpush-http2-00

**Comment by efullea** [comment]
I support using "application server"

**Comment by mvano** [comment]
Where does that leave the term "webapp" then? Should it be:
- Webapp
- App
- Application

**Comment by efullea** [comment]
I think 'webapp' is fine in this case as AFAIU it is the scope of this W3C spec.

**Comment by beverloo** [comment]
Agreed.

**Comment by martinthomson** [comment]
SGTM.  As long as we consider 'webapp' to be resident on the 'device', that works out.

I don't want to start using webapp except in providing context, because I think that the protocol aspects of this could go beyond the web.
