### ISSUE TITLE
Force confidentiality and integrity protection (encryption)

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#55]
After doing the threat analysis on the protocol pieces of this, the only major concern was the availability of push messages to the push server itself.  Much of the rest of the system can be protected with HTTPS, but if we don't trust the push server, then there isn't anything we can do.

Applications are trivially able to provide confidentiality and integrity for push messages - they are talking to themselves, after all - but the path of least resistance is to send messages in the clear.  We can do better than that.

The idea here is to include a [WebCrypto key](http://www.w3.org/TR/WebCryptoAPI/#key-interface) with each push registration created by the application.  The browser will reject messages that aren't [JSON Web Encryption](https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-33) objects that are encrypted and authenticated with the provided key.

**Comment by beverloo** [comment]
I like and agree with the idea, but before adding mandatory encryption to the Web Push API I would like to be sure that we can support encryption for 1 (application server):many (recipients) push message distribution. (Which is in scope for the IETF Web Push group to solve.)

**Comment by miguelgarciaarribas** [comment]
Here is how I see this being implemented.

The [PushRegistrationInterface](http://www.w3.org/TR/push-api/#pushregistrationmanager-interface) would look like this:

interface PushRegistration {
    readonly    attribute DOMString endpoint;
    readonly    attribute DOMString registrationId;
    **readonly   attribute Key[] encryptionKeys;**
};

Where Key is defined in the [WebCrypto API](http://www.w3.org/TR/WebCryptoAPI/#dfn-Key).

The web developer would use Key.algorithm to detect what encryption algorithm (and any necessary parameters) each key is for, then export the key (to upload to their server) in the KeyFormat of their choice using crypto.subtle.exportKey(KeyFormat, Key) (which is available in both windows and workers).

It is not clear to me if the W3C spec itself needs to list explicit algorithms supported, but we should start talking about them somewhere. Martin, could you perhaps start that conversation in the IETF webpush list?

**Comment by miguelgarciaarribas** [comment]
I dropped a pull request with this so that we can comment there.

https://github.com/w3c/push-api/pull/89/commits

**Comment by martinthomson** [comment]
Basic changes merged.  Will close and iterate on new changes.
