### ISSUE TITLE
Remove registrationId

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#56]
Currently, a registration looks like this:

``` webidl
interface PushRegistration {
    readonly    attribute DOMString endpoint;
    readonly    attribute DOMString registrationId;
};
```

Which is two values, which are used in two ways:
1. both together, they are used to send a message
2. `registrationId` is used to identify a registration in the API

Requiring two identifiers is a burden on the application when it comes to sending messages.  The proposed web push protocol needs a single URI only.  The push server can embed any information it needs in the URI.

Using the same identification that the push server uses in the API is also unnecessary.  Other APIs, if they have some sort of identification, use identifiers that are minted by the browser.  Given that we (currently) have only a single URI per origin, we don't need to perform this identification at all.

I'd like to propose the removal of `registrationId`.

**Comment by efullea** [comment]
We have considered having a single attribute (endpoint) in the past, as you propose. However it reduces flexibility, whilst the burden it saves to the app is minimal. Having two parameters allows splitting the webapp instance specific part, i.e. the registrationID, from the push service generic part, i.e. the endpoint, which may be unique for all app instances. If I recall correctly there were some concerns also that having the registrationID as an URL parameter could imply some security issues, e.g. if the URL is logged as plain text in a proxy.

**Comment by martinthomson** [comment]
I'm aware of that discussion.  I'm not sure what sort of flexibility you think a split gains, but the privacy implications of what you describe (i.e., correlation) are not particularly good.

I'm working on a proposal for one-to-many push messaging and two items doesn't work particularly well there.  That, plus the reasons above, leads me to conclude that there isn't any value in a split.

The proxy logging issue is addressed by using end-to-end confidentiality measures.  I've heard this logging issue many times in the past, but it turns out to be bogus.  I've deployed several solutions that relied on confidential URLs successfully, and while security review always identified the need to ensure confidentiality, this was never an issue.  The logging issue is better addressed with security guidance (which amounts to no more than advice on good operational practices).

**Comment by efullea** [comment]
What are the privacy implications that you refer? Even if we have a single attribute it would be correlated with the webapp instance to which it refers.

I don't know what kind of issues you are finding for the one-to-many use case, but IMO having two separate parameters does indeed simplify that use case. The application server can determie which webapps are handled by the same push server (those having the same endpoint) and can send one-to many push messages by sending a set of 'registrationID' elements to that server.

Regarding your statement on the proxy logging issue being a bogus, it is not what I hear from our security experts. Also it is well known that if something can be done wrong it will be done wrong at some point, regardless the security guidance you provide. No need to give examples, a lot out there.

**Comment by martinthomson** [comment]
The privacy issue depends a great deal on scale.  It's not clear from the current API whether that is good (large values of K) or bad (small K).  What is clear is that the split is unnecessary, and it seems to address only one concern: this logging security point.

I'm not going to respond to an appeal to authority on the logging point.  We can each trot our security experts.  My point was not that this logging issue is non-existent, it's just that it's largely FUD.

**Comment by costinm** [comment]
The registration includes 3 types of information:
- information about the server delivering push notifications
- identity for the app and device
- some form of credentials

Combining all 3 in one URL doesn't seem a common practice - most HTTP protocols separate credentials at least. I don't have a problem with combining the push endpoint URL with the identity, but if the credentials are included in the URL we are going to make it very hard to use anything but bearer tokens, and will be pretty hard to keep their life short. ( because the URL is opaque - having separate credentials allow other schemes, like digest variants )

Oauth2 (and I don't know any other protocol) allows tokens in URL, but they're very short lived, while registrations need far longer life to be useful, you can't renew it every hour.

**Comment by martinthomson** [comment]
If we define separate values, then mechanisms have to be defined for how those values are carried in a protocol.  That complicates the protocol unnecessarily.  And - most importantly - it complicates its use.

The point you make about alternative authentication mechanisms actually only reinforces this point.  If we want to do the authentication portion using oauth, then we would need to define a profile of oauth, which is difficult to get right.  Or we could invent a new HTTP authentication scheme (as is the current vogue), or just re(ab)use Basic or Digest.

On the other hand, if the relevant information is left opaque to the user, then use is trivial.  As long as we're willing to accept the limitations of using a bearer token for authorizing pushes, then embedding in the URL is the easiest to use.

That said, there are use cases for adding oauth or similar additional authentication layers to a registration, which I am interested in at least exploring.  If it turns out to be necessary for applications to be more aware of the authentication process, then that can be done.  At this stage, I'm not seeing any reason that we would want to do that, unless we decide that we want to resort to zero-knowledge proofs, PAKE or something equivalently complex.  I'd hope that anything like that would be strictly optional.

**Comment by costinm** [comment]
On Mon, Oct 20, 2014 at 8:18 PM, Martin Thomson notifications@github.com
wrote:

> If we define separate values, then mechanisms have to be defined for how
> those values are carried in a protocol. That complicates the protocol
> unnecessarily. And - most importantly - it complicates its use.
> 
> The point you make about alternative authentication mechanisms actually
> only reinforces this point. If we want to do the authentication portion
> using oauth, then we would need to define a profile of oauth, which is
> difficult to get right. Or we could invent a new HTTP authentication scheme
> (as is the current vogue), or just re(ab)use Basic or Digest.
> 
> Well, in effect we are inventing an HTTP authentication scheme - but far
> worse than any of the alternatives, even Basic authentication is better
> than having the credentials part of the URL.

Having the values carried in the protocol seems pretty simple if we agree
to have metadata ( i.e. HTTP headers ), we just need to define
a well-known name.

Complicating the use is true - as any security does :-), but I think it's
usually expected and accepted to use authentication on APIs.

On the other hand, if the relevant information is left opaque to the user,

> then use is trivial. As long as we're willing to accept the limitations of
> using a bearer token for authorizing pushes, then embedding in the URL is
> the easiest to use.
> 
> How about something in the middle: use a bearer token ( as it is indeed
> easy to use ), but pass it as metadata in the registration (i.e. separate
> from
> the URL), and pass it as a header in requests.

At least you can decouple rotation/refresh of the auth token from the
registration ID, and future spec updates can define new auth
schemes if needed, without breaking backward compat and requiring changes
on client side or in UA->push server communication.

> That said, there are use cases for adding oauth or similar additional
> authentication layers to a registration, which I am interested in at least
> exploring. If it turns out to be necessary for applications to be more
> aware of the authentication process, then that can be done. At this stage,
> I'm not seeing any reason that we would want to do that, unless we decide
> that we want to resort to zero-knowledge proofs, PAKE or something
> equivalently complex. I'd hope that anything like that would be strictly
> optional.
> 
> Agreed - it should be optional, but at least possible.

If we define registration as a (endpoint URL, identity and list of
metadata/headers) - or even combined URL and identity, and separate list of
headers -
than complex schemes can be implemented where needed, without
complexity/changes in the client code / javascript API or UA-push server
protocol.

Costin

**Comment by pwnall** [comment]
I implemented a node.js server and JS library based on this Push API specification. I found the `endpoint` / `registrationId` separation useful.

Code:
https://github.com/pwnall/w3gram-server
https://github.com/pwnall/w3gram-js

More specifically, it lets me say that application servers can reuse an HTTP connection to push messages to multiple devices when the endpoint is the same.
https://github.com/pwnall/w3gram-server/blob/master/Protocol.md#server-api

I hope this input is useful.

**Comment by martinthomson** [comment]
@costinm 

> Well, in effect we are inventing an HTTP authentication scheme - but far worse than any of the alternatives, even Basic authentication is better than having the credentials part of the URL. 

This is not a new technique, and I'd disagree with the characterization as a new scheme.

> Having the values carried in the protocol seems pretty simple if we agree to have metadata ( i.e. HTTP headers ), we just need to define a well-known name.

That's a decidedly non-simple thing if you want to talk standardization.  I know that people mint private-use things all the time, but the bar to clear is in a very different place if you are talking about the IETF.

> At least you can decouple rotation/refresh of the auth token from the registration ID, and 

Defining two things does nothing to save the application work.  They still have to deal with the refresh by sending data to the application server from the device.

> future spec updates can define new auth schemes if needed, without breaking backward compat and requiring changes on client side or in UA->push server communication.

It's far easier to add something here than remove it if you want to talk about back-compat.

@pwnall 
That's interesting; are you aware of the effort in the IETF to define a protocol?  It's a little more streamlined than the one you describe.

> I found the endpoint / registrationId separation useful. [...]
> More specifically, it lets me say that application servers can reuse an HTTP connection to push messages to multiple devices when the endpoint is the same.

That's true no matter where we decide the bearer token is held.

**Comment by pwnall** [comment]
@martinthomson I read some conversations alluding to a standard protocol, but did not see the document. Can I please get a link to it? I'd love to switch over to a (draft) standard, if it exists.

Also, would it be possible to add a non-normative reference to the IETF draft?

**Comment by costinm** [comment]
@martinthomson  - is there any standard defining the use of long lived authentication tokens in URL for HTTP authentication ? I only know of oauth2, but with very short lived tokens. All other HTTP auth schemes I know use headers.

Almost all IETF standards I know have some (extensible) headers or metadata - HTTP, MIME, even IP has options, and most support multiple authentication schemes that are (partially) orthogonal with the core protocol

**Comment by martinthomson** [comment]
@pwnall it's only a proposal currently: https://tools.ietf.org/html/draft-thomson-webpush-http2

@costinm Yep. RFC 5808 describes exactly the mechanism I'm advocating for.  It's not generic in the sense that perhaps you might be looking for, but that's more or less the point: it doesn't actually need to be _defined_ really.

**Comment by costinm** [comment]
I don't know how commonly implemented RFC5808 is - so far most web APIs I
know use Oauth2, Basic or variants of oauth1/digest,
I don't know any common API using RFC5808 for authentication. I assume you
mean variant 3.3.4 (  Possession authorization model ) -
that means the spec would be stuck with bearer tokens and no clear option
to provide different authentication mechanisms.

I think it's ok to specify that push servers may use RFC5808 and not
require any additional authorization, but
since HTTP is used for transports I think it's reasonable to allow at least
what HTTP does for authentication, optional as well.

**Comment by martinthomson** [comment]
I think that this covers the entire argument so far: http://www.w3.org/TR/capability-urls/  (I'd forgotten about this document until I was just reminded of it.)

My assessment remains the same.  Most of the reasons for doing this apply; a couple of the reasons against it don't apply.  The risk of exposure is the only major reason against, and that's mitigated fairly easily by the existing need to manage lifetimes.

**Comment by costinm** [comment]
On Fri, Oct 24, 2014 at 12:06 PM, Martin Thomson notifications@github.com
wrote:

> I think that this covers the entire argument so far:
> http://www.w3.org/TR/capability-urls/ (I'd forgotten about this document
> until I was just reminded of it.)
> 
> The abstract seems to cover most of it:  "There are times when this is
> useful, for example one-shot password reset URLs, but overuse can be
> problematic as URLs cannot generally be kept secret."
> The use cases described are not even remotely closed to push.
> 
> My assessment remains the same. Most of the reasons for doing this apply;
> a couple of the reasons against it don't apply. The risk of exposure is the
> only major reason against, and that's mitigated fairly easily by the
> existing need to manage lifetimes.

I think there are more major reasons against requiring all push services to
use resource URL as the only mean of authentication.
For example:
- it's not extensible - HTTP supports quite a few evolving schemes for
  authentication. A fixed URL is harder to evolve.
- while I agree there are some common uses ( password reset, access to
  shared items without accounts) - the typical forms of authentication are
  far more broadly
  used and proven. Even 'basic' authentication seems to be better that this (
  no risk of exposure - and quite simple, even http includes it :-).
- the use case described are quite different - the examples don't include
  any programmatic API, they are (as it should be) use cases where a
  URL is shared in a medium and used with GET requests by a browser, which is
  perfect use case for capability-urls, but quite different from a
  typical API.

Something simpler than HTTP - including a simpler authentication scheme,
like the capability-url - may be desirable, but I don't think
push api is the right place to require them. I don't have a problem with
defining it as one option - but we should define at least
a second more traditional scheme.

The are other benefit of clearly generating an URL, an ID and 'credentials'
as separate values - the URL will identify the push
server, the ID can be used to identify the app even if the push server URL
changes ( some implementations may use multiple
send URLs ), and credentials can be rotated without changes to URL or ID.

**Comment by martinthomson** [comment]
> The use cases described are not even remotely closed to push.

I don't see how that's a problem.  The properties they exhibit are similar.

> I think there are more major reasons against requiring all push services to use resource URL as the only mean of authentication.

I never meant to suggest that this would be the only way, just the default way.

> it's not extensible 

The system we have is absolutely extensible.  We can still request and return additional authentication constraints on a resource URL.  The fact that they have to be requested might be considered a downside, but I don't see it as a big problem.

> the typical forms of authentication are far more broadly used and proven

https://yourlogicalfallacyis.com/bandwagon :)

> the use case described are quite different - the examples don't include any programmatic API, they are (as it should be) use cases where a URL is shared in a medium and used with GET requests by a browser, which is perfect use case for capability-urls, but quite different from a typical API

Actually, this is the reason that some of the negatives regarding capability URLs don't apply.  The risk of exposure here is vastly diminished because the link is highly unlikely to surface anywhere other than the logs of the push server, which can easily be configured to avoid that (see https://tools.ietf.org/html/draft-thomson-webpush-http2-01#section-9.4).

> we should define at least a second more traditional scheme.

I am definitely interested in exploring what alternatives might look like.  Here's a quick strawman:

``` js
foo.register({ authentication: "basic", username: "john" }).then(registration => {
  // registration.url is an endpoint, like "https://push.example/dhoihwefoihasd"
  //  ... and the URL could be lower-entropy if that can be added to the password
  /// ... but it probably won't be
  // registration.authentication is "basic"
  // registration.username is "john"
  // registration.password is random junk "dbfoidoiher09fgilpj635"
});
```

The key here is that the application opts in to an authentication method, so we have a clear signal that it is willing to do that and a definite point at which the application can see that its request was understood and accepted.

**Comment by costinm** [comment]
On Wed, Oct 29, 2014 at 10:22 AM, Martin Thomson notifications@github.com
wrote:

> The use cases described are not even remotely closed to push.
> 
> I don't see how that's a problem. The properties they exhibit are similar.
> 
> What properties ? And which are needed for webpush ?

For a password reset - which may be sent in an email - capabilities URLs
seem a good fit, user can click without any
extra overhead. For sharing a resource - same.

The main property seems to be including server location, resource ID and a
mean of authentication in a single URL,
and that's perfect for the use cases they seem to be using it for.

We don't really need this - and the fact that it is possible to stuff all
of them together doesn't mean we should.

GCM does exactly this - if you add some http://gcm.googleapis.com/ in front
of the registration ID you get a capability URL. We had used this for 4
years - it's not working very well.
Developers want to know which part is the ID, the auth part needs to be
rotated often - and there are parts of the
'opaque' that have specific uses, are only needed for a short time.

HTTP - with URL and headers/metadata - provide a more flexible model, where
things like encryption key can
be returned separately from authenticator or service URL. Some
implementations may want to return multiple service URLs, or provide
provider-specific features.

That's the point of HTTP headers - the common ones are defined, but more
specs can extend it.

>  I think there are more major reasons against requiring all push services
> to use resource URL as the only mean of authentication.
> 
> I never meant to suggest that this would be the only way, just the default
> way.
> 
> IMHO default is to return a URL and a set of headers, which the user app
> needs to pass to its server.

If an implementation wants to return only one opaque URL - that's
absolutely fine, but apps should
expect metadata and sent it up.

>  it's not extensible
> 
> The system we have is absolutely extensible. We can still request and
> return additional authentication constraints on a resource URL. The fact
> that they have to be requested might be considered a downside, but I don't
> see it as a big problem.
> 
> Yes, the request for registration ID also needs to provide metadata.

This is a 'web' standard - so I don't see why we spend so much time
discussing having metadata
in request and response. The UA will make a HTTP request to the push server
- and that will
  pass and return headers.

>  the typical forms of authentication are far more broadly used and proven
> 
> https://yourlogicalfallacyis.com/bandwagon :)
> 
> The fact that it's popular for web services to use certain common
> authentication schemes doesn't make
> them wrong. And leperchauns exist !
> 
>  the use case described are quite different - the examples don't include
> any programmatic API, they are (as it should be) use cases where a URL is
> shared in a medium and used with GET requests by a browser, which is
> perfect use case for capability-urls, but quite different from a typical API
> 
> Actually, this is the reason that some of the negatives regarding
> capability URLs don't apply. The risk of exposure here is vastly diminished
> because the link is highly unlikely to surface anywhere other than the logs
> of the push server, which can easily be configured to avoid that (see
> https://tools.ietf.org/html/draft-thomson-webpush-http2-01#section-9.4).
> 
> Risk of exposure is not my concern, neither logs (it is a pain to avoid
> logging the URL, but it is possible).

My top concern is mingling of completely different elements in an opaque
URL (or string in GCM case).

 we should define at least a second more traditional scheme.

> I am definitely interested in exploring what alternatives might look like.
> Here's a quick strawman:
> 
> foo.register({ authentication: "basic", username: "john" }).then(registration => {
>   // registration.url is an endpoint, like "https://push.example/dhoihwefoihasd"
>   //  ... and the URL could be lower-entropy if that can be added to the password
>   /// ... but it probably won't be
>   // registration.authentication is "basic"
>   // registration.username is "john"
>   // registration.password is random junk "dbfoidoiher09fgilpj635"});
> 
> The key here is that the application opts in to an authentication method,
> so we have a clear signal that it is willing to do that and a definite
> point at which the application can see that its request was understood and
> accepted.

That's very close to what I'm suggesting - register() should take in
metadata, and the result should
contain metadata too.

In particular: at least the 'end-to-end' encryption key should be returned
as a separate (and spec-defined) header,
as well as a public key.
I think if we really want to require encryption - it should require at
least symmetric key, with public optional.

And as with incoming messages, some of the metadata will be from the UA (
the e2e keys ), some
from the push server.

**Comment by paul-em** [comment]
Maybe i misunderstand something in the whole concept here, but shouldn't the AppServer not have to authenticate against the PushServer? This would mean you have to register for every PushServer out there and this does not really contribute to an decentralised web.
Having a long enough registerId and same origin restrictions (there are same origin restictions, right??) should do the trick in my opinion.

And concatenating endpoint and registerId would make no benefits in my eyes.
Say the endpoint is "https://android.googleapis.com/gcm/send" and the registerId is something like this "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx" (only way longer).

You can now send the notification from your AppServer via POST with header "Content-Type:application/json" and body: 

``` javascript
{
  "registration_ids" : ["APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx"],
  "data" : {
    ...
  },
}
```

In this way, if you want to send the same message to multiple clients you can just loop through your clients and group the ones with the same endpoint.

This is basically how GCM works right now, only with API Key.
https://developer.android.com/google/gcm/http.html#response
