### ISSUE TITLE
push-register (pushregistrationlost / pushsubscriptionchange) behavior when clearing browser cache

### ISSUE THREAD

**Issue by beverloo** [w3c/push-api#61]
The specification does not define whether the `push-register` (or `pushregistrationlost`) event should be invoked when a user clears their browser cache/cookies.

While this is part of the larger question of Push + browser cache problem, it would be good to nail down for the `push-register` event and in the privacy section what the expected behavior is.

Straw-man: We must not invoke `push-register` (or `pushregistrationlost`) when the user clears their browser cache. The UA could provide for an interface themselves to clarify to the user that expected functionality might be lost.

**Comment by johnmellor** [comment]
If clearing the cache clears Service Workers, then there wouldn't be anywhere to deliver the event to anyway.

**Comment by martinthomson** [comment]
Any identifiers that are generated by the API need to be cleared when cookies are cleared.  Clearing cookies is usually a trigger for removing tracking mechanisms, and registration identifiers are definitely tracking mechanisms.

**Comment by beverloo** [comment]
We have this covered in the `Security and privacy considerations` section.

> When a service worker registration is unregistered, any associated push subscription must be deactivated.

Clearing data deletes the Service Worker registration, which deactivates the push subscription, which (eventually) tells the push service, that then can tell the application server.

**Comment by delapuente** [comment]
How exactly does the push service tell the application server that the subscription has been deactivated?

**Comment by ghost** [comment]
@delapuente The app server will get a 404 or a 410 when it tries to send to the subscription.

**Comment by delapuente** [comment]
Thank you.
