### ISSUE TITLE
Use ExtendableEventInit instead of EventInit

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#78]
See https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#extendable-event

**Comment by martinthomson** [comment]
For what exactly?

**Comment by mvano** [comment]
All events fired in service workers should inherit from `ExtendableEvent` and therefore their init object should inherit from `ExtendableEventInit` rather than `EventInit`.

**Comment by bashi** [comment]
Also note that when an attribute is added to `ExtendableEvent` and its initializer into `ExtendableEventInit`, the attribute won't be initialized when `PushEventInit` directly inherit from `EventInit`.

At least, we should do either:
- Make PushEventInit inherit from ExtendableEventInit
- Make PushEvent directly inherit from Event (not ExtendableEvent)
