### ISSUE TITLE
Consider exposing meta-information on push message

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#81]
The current API defines push message as a DOMString.  However, the proposed protocol exposes some meta-information that might be useful.

For instance, a pushed message could include an indication from the push server about the time that it received the message, which could be earlier than the time that it was delivered.

A generic metadata channel, such as HTTP header fields, might be the most capable interface in this regard.  A subset of https://fetch.spec.whatwg.org/#responses might be appropriate.

**Comment by mvano** [comment]
What information are you thinking of that cannot be bundled in the payload by the application server itself? Your example of "time push server received message" could instead be "time message was sent by application server" and that's fully within control of the application.

**Comment by beverloo** [comment]
The difference between the time at which the push service received the message from the application server, and the time it was able to deliver it to a device seems like something which doesn't have to be captured by either protocol, and is an implementation detail of the statefullness provided by the push service (which in itself is not required).

I agree with Michael that such information could be included in the data payload itself. Relaying information about advanced features such as TTL and collapse keys might be interesting, but I'd be interesting to hear what use-cases this would address, given that these are mostly server-sided concerns.

**Comment by martinthomson** [comment]
Yeah, I'm not seeing much reason not to push this out.

**Comment by costinm** [comment]
Any information provided by the push server itself can't be included in the encrypted payload:
- in case of multiple (authenticated) senders/channels - the identity of the sender/channel
- timestamps
- Via ( if app needs to debug which push server delivered the message for example )

I suppose most of the other use cases for having headers in HTTP apply to this as well. 

Having only a DOMString excludes any information that could be provided by the push server, due to encryption.

**Comment by martinthomson** [comment]
One thing that we might want to consider in this context is whether the delivery of strings, binary data, or both is worth doing.  I have opened #83 to cover this question, in which one of the options requires some sort of meta-information.

**Comment by rektide** [comment]
I registered some concerns about Push API's inability to expose meta-data on the mailing list, and have just become aware of this issue here.
http://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0257.html

I most emphatically would appreciate a Push API capable of transmitting resources. Sending opaque message blobs is a major step back into the dark.

**Comment by rektide** [comment]
The number 1 most important meta-information I want about pushed data is a URL. Without a url data is just data- with it, it's information, discretely identifiable information.

Attaching http headers to the push would be a very close number 2.

I hope to see progress on getting these optional fields into the spec.

**Comment by mvano** [comment]
We should aim to keep this API as small as possible, so we can get multiple compatible implementations sooner. In addition, as phrased, this is quite a general feature with only lightly defined use cases. I think for a piece of metadata to make it into the spec we need:
- An issue for that specific piece of metadata so we can have an uncluttered discussion about it
- Use cases for that specific piece of metadata

I think this discussion has served its purpose, so I'll close it.

**Comment by rektide** [comment]
Web developers are well practiced at using HTTP to transmit resources. Giving them the ability to use resourceful semantics- header+body- to transmit resources, as they do with technologies like HTTP/2 Push- and having those resources appear in the Push API is something that I would wager 85% of web developers would say is as small, uncluttered, and use-case friendly as possible.

The idea that each piece of meta-data would need individual approval works counter to flexibility that has enabled the last two decades of web development; no one needs permission to add headers. Headers are an open extensibility mechanism.

What is needed to re-open this ticket or to create a sufficient starting place for a follow-up ticket?
