### ISSUE TITLE
Strings or binary or both

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#83]
Push messages are severely space constrained (for good reason).  This is worse if we adopt mandatory encryption (and we should).

This creates an incentive to find ways of packing data as densely as possible.  That means binary payloads are quite desirable.  Do we want to enable binary data delivery?

Obviously this creates some complexity for applications.  Strings are still the most accessible form for messages.  I see several options:
1. binary data only
2. deliver both, with a string value only populated if it can be decoded successfully
3. deliver either and deliver a signal in the protocol, just like in thewebsocketprotocol or WebRTC

My initial leaning is toward 2.  I despise 3, though recognize that it may be necessary.

**Comment by costinm** [comment]
HTTP (and every other protocol) handles this with Content-Type or similar meta-information. 
I'm not sure having the UA guess if the decrypted payload is a string is most efficient / robust - 
I would suggest meta-data, or 1 (binary data) plus some helper to decode it to string. 

Most apps know what their servers are supposed to be sending.

**Comment by rektide** [comment]
Fetch API has a Body mixin that has an example, where the data is reified once and only once via a Promise (calls to different accessors fail). This might be a potential model for number 3, either.
https://fetch.spec.whatwg.org/#body-mixin

**Comment by johnmellor** [comment]
Binary payload + Content-Type header + Fetch API's Body mixin for easy decoding to string / JSON / etc as appropriate sounds great.

(having the payload be a DOMString was a kludge caused by there being nothing as simple as the Body mixin when we designed it; but no-one was really keen on requiring Base64 or similar for binary data)

How would we actually expose the Content-Type header? As a Fetch API [Headers](https://fetch.spec.whatwg.org/#headers) object? I guess that'd mean we have to standardize the meaning of various headers in a push context.

**Comment by martinthomson** [comment]
That might work.  If we can just lift the work that Fetch does, that's even better.

This is, however, somewhat incompatible with the proposed security enhancements (see #55) in that the metadata @costinm is describing will be on the outer envelope and cannot describe the actual message contents, post decryption.

**Comment by costinm** [comment]
The outer envelope is generated by the Push server and/or UA - it is mostly
independent of the encrypted payload.
The encryption is intended ( among other things ) to prevent the push
server to access or modify the content of the message.
The metadata provide information from the push server, related to the
delivery and origin of the message.

**Comment by martinthomson** [comment]
That was not the concern.  When talking about integrity protection for HTTP requests, you inevitably need integrity protection for some part of the metadata also, lest you invite attacks that rely on misinterpretation.  For instance, `application/foo+json` might be easily confused for `application/bar+json` since they are both processed in similar ways.

If we had very specific metadata that was carried, we could make clean guarantees about what entity each item was attributed to and thereby minimize the exposure to this sort of attack.  However, if we allow metadata to be mixed, or there is a generic structure, this gets more complex.

I think that I'd like to focus on identifying what use cases currently use meta-information and we can then determine - for each of those - what is required to support those use cases.

**Comment by martinthomson** [comment]
I'll note here, since it appears that I lost track of context: for this issue (binary/text/both), the metadata would need to be signaled inside the encrypted object.  Or we could use the same sort of mixin that Fetch does, implying that the application receiving the data would know best.  I like the mixin idea a lot.

**Comment by costinm** [comment]
There are 2 types of 'metadata': provided by the push server (or UA), and
originated from the sender.
I don't think you need an exhaustive list of all headers - HTTP doesn't
define it either.

It's pretty easy to define a prefix that is reserved for webpush server,
and app can decide what headers to use or trust.
(gcm defines 'google.' prefix, it also defines 'from' for example as
'pushsever reserved')

Or define a prefix for headers that originate from the sender, and have
them signed (there are ways to do that) with the
encryption key.

(the assumption is that some of the headers originating from sender may be
used as part of delivery - collapsing,
TTL, priorities or whatever future extensions we may add )

**Comment by martinthomson** [comment]
OBE
