### ISSUE TITLE
Push API should be allowed without dependency on service worker 

### ISSUE THREAD

**Issue by ShijunS** [w3c/push-api#84]
As suggested by Arthur Barstow, copy Bug #27108 from Bugzilla.

Shijun Sun     2014-10-20 15:52:24 UTC  
Open a bug to track the topic on the mailing list.
http://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0179.html 

When the "push client" can handle generic actions (such as posting a toast notifications) waking up the browser (or a subset of it) and let service workers to display each notification might not be the best practice from performance perspective, especially when the user does not want to pick up each incoming video call or read each incoming emails right away.  The Push API spec should allow the web developers to have flexibility to leverage the generic actions, or rely on a service worker, or maybe do both.

I expect the generic message types should be scoped to a very small set.  Toast notification with a text message and an optional image should be a good starting point.  This will also lead to extensions to existing API.  For example, we should allow a webapp to construct a PushRegistrationManager based on a valid registrationId it got previously.  We should think through the details in the WG.

BTW, Martin Thomson mentioned another scenario [1] in the mailing list that can also benefit without having the service worker dependency.

[1] http://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0140.html

Comment 1  Anne     2014-10-20 15:58:34 UTC  
What's the problem with requiring a service worker?

Comment 2  Arthur Barstow     2014-10-20 16:05:48 UTC  
[ Bryan, Eduardo, Michael - rather than track Push API bugs via Bugzilla and Github Issues, perhaps you should converge on one (probably Github). ]

Comment 3  Chris Wilson     2014-10-20 16:06:47 UTC  
Even more directly - what's the Push "client", if not code inside the SW?  How do you "handle" actions without somewhere to hang that code?

Comment 4  Shijun Sun     2014-10-20 16:15:24 UTC  
(In reply to Chris Wilson from comment 3)

> Even more directly - what's the Push "client", if not code inside the SW? 
> How do you "handle" actions without somewhere to hang that code?

Based on Fig. 1 of the spec, the client is implemented in the UA or the system it runs on.

**Comment by jakearchibald** [comment]
Strongly disagree, for the reasons in http://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0182.html

**Comment by mvano** [comment]
I also strongly disagree with this suggestion. The discussion on public-webapps captures exactly why this is unlikely to address web developer's needs, as they more complex and still evolving. It is a premature optimization.

**Comment by mvano** [comment]
Note though, that it's not a bad idea per se. It's a clear opportunity for optimization, but the form the optimization needs to take will not be clear until the lower level API gets significant usage.

**Comment by ShijunS** [comment]
Based on our conversations with Alex Russell [1], we can’t rely on a Service Workers being always available to process incoming push requests and notification clicks.  The lifetime of a Service Worker is determined by the User Agent runtime.  Based on our understanding the current Chrome implementation aggressively kills SW to reduce the tax on memory, CPU, and networking.  Therefore, having a generic mechanism to handle the incoming requests is not just a performance optimization approach but required to ensure we handle incoming requests. In addition, we could push the same request to the SW if it is available.

[1] https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/QfxPGw0kJW8

**Comment by johnmellor** [comment]
> we can’t rely on a Service Workers being always available to process incoming push requests and notification clicks.

There's been some misunderstanding about SW lifetime. Let me try to clarify the intention of the SW spec: SWs are normally stopped, and are _started on demand_ to handle events like push, fetch, etc. Starting a SW is intended to be a cheap operation - when the JS file is executed*, authors should only register event handlers. Thus the SW is always able to handle incoming events, even if it wasn't yet running.

Once the SW has handled the event (which may include waiting for Promises passed to event.waitUntil - see #85), they will usually be killed again. In practice, UAs may keep them alive a little longer as a performance optimization (e.g. whilst a controlled page is loading, it's likely that there will be many fetch events due to subresource loads or XHRs, and it would be wasteful to start and stop the SW for each fetch), but authors should not rely on this (e.g. by storing globals).

*: (a smart VM might even be able to snapshot the state of the SW script after executing the JS file, then on subsequent startups simply restore that snapshot)

**Comment by ShijunS** [comment]
As discussed in the WG session at TPAC, I'm sharing the initial thinking on the interface.

``` javascript
partial interface PushRegistrationManager {
    Promise<PushRegistration>     register ( optional PushNotificationOptions options ); 
    PushNotificationOptions?      getPushNotificationOptions (); 
};

dictionary PushNotificationOptions {                       
    boolean systemNotificationEnabled = false;
    DOMString lang = "";                                      // BCP 47 language tag
    DOMString dir = "auto";                                   // "ltr", "rtl", "auto"
    DOMString sound = "";                                     // "auto", "ringtone", ""
};
```

As a reference, here is the [link to the deck presented at TPAC](http://lists.w3.org/Archives/Public/public-webapps/2014OctDec/att-0283/RTC_and_Push_scenario.pdf).

**Comment by mvano** [comment]
I think there is consensus on the public-webapps mailing list [1], at TPAC [2], and in this repo, that maintaining a dependency on service workers is appropriate. It exposes the push functionality at a low and flexible level that is composable with other APIs and allows for common patterns to evolve. Google's Chrome team has also summarized their position on the pros and cons of an imperative vs a declarative approach in [3].

I think many people also agree that there is an opportunity for optimization by combining several APIs into one (a "declarative" API) that would avoid running a service worker in certain cases. However, specifying and implementing this would be a significant amount of work, and there is not currently a lot of agreement on what the feature set would be. It has been suggested to collect use cases, and performance data and requirements, that would inform such an effort. Potential spec dependencies of such an integrated higher level API are the Push API [4], the Notifications API [5], the Telephony API [6], and the WebRTC API [7].

As such, I'd like to leave this issue open but mark it as an enhancement for a future version of the Push API, or maybe as the basis for a separate spec that depends on the Push API.

[1] https://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0135.html
[2] http://www.w3.org/2014/10/27-webapps-minutes.html#item23
[3] https://docs.google.com/document/d/1kpTbKoPRaB4lXD6AMTCV2U5gTEPssQnqJj70KNb97SI/edit?usp=sharing
[4] https://w3c.github.io/push-api/
[5] https://notifications.spec.whatwg.org/
[6] http://sysapps.github.io/telephony/
[7] http://w3c.github.io/webrtc-pc/

**Comment by martinthomson** [comment]
I don't think that we can do this.  @ShijunS, do you think that this is necessary still?

**Comment by ShijunS** [comment]
@martinthomson, We can close the issue and revisit the topic in the future if there is opportunity for optimization along the direction.

**Comment by martinthomson** [comment]
Thanks.
