### ISSUE TITLE
Push subscription should require active Service Worker

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#92]
During initial service worker registration it won't be active right away. It might fail to activate. One problem with this is that push events cannot be delivered to such a worker yet. To avoid potential message loss here, Push registration should reject if there is no active service worker yet.

Note that the Notification API has a similar requirement: https://notifications.spec.whatwg.org/#service-worker-api

@annevk @jakearchibald @beverloo - does this sound right?

**Comment by annevk** [comment]
Yeah.

**Comment by annevk** [comment]
I think we basically want this for any API on top of service workers.

**Comment by mvano** [comment]
Peter noted that we can just wait for the SW to be activated, the promise callbacks can wait a little. That seems like a nice way of avoiding rejection in this possibly common case (thanks John):

``` js
navigator.serviceWorker.register(...).then(function(serviceWorkerRegistration) {
    serviceWorkerRegistration.pushManager.subscribe(...);
});
```
