### ISSUE TITLE
endpoint should be of type URL not DOMString

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#93]
The endpoint is currently defined as type `DOMString`, which is an absolute URL. Any objections to actually making it of type `URL`?

**Comment by martinthomson** [comment]
By which you mean: https://url.spec.whatwg.org/#api ?  That seems OK.

**Comment by mvano** [comment]
Yes, that's the one I was thinking of. However, the spec states that we should just expose a string [1]:

> A standard that exposes URLs, should expose the URL as a string (by serializing an internal URL). A  standard should not expose a URL using a URL object. URL objects are meant for URL manipulation. In  IDL the USVString type should be used.

So we might change it to USVString. @annevk is that correct?

[1] https://url.spec.whatwg.org/#url-apis-elsewhere

**Comment by annevk** [comment]
Yes. Please don't expose it as a mutable URL object.
