### ISSUE TITLE
unregister() should be available on the PushRegistration object

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/push-api#94]
I think it would be great to follow the pattern of ServiceWorker:
- unregister() should live in PushRegistration;
- unregister() should return a Promise<boolean> that says whether the unregistration happened.

CC: @annevk and @jakearchibald

**Comment by mvano** [comment]
Agreed it would be good to align this with the sw spec, no need to do something different for a very similar feature. For reference, here's the sw unregister method definition: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#navigator-service-worker-unregister

**Comment by mounirlamouri** [comment]
Fixed by #97.
