### ISSUE TITLE
.getRegistration() should not reject if there is no registration (but return a null object)

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/push-api#96]
CC @jakearchibald

It seems to be the pattern generally being used with Promises. Rejecting should be an exceptional case. In that case, having no registration isn't exceptional, it's definitely expected.

Also, as @jakearchibald pointed, it would allow to do things like that in ES7:

``` javascript
var reg = await push.getRegistration();
```

**Comment by mvano** [comment]
Do you have references to `the pattern generally being used with Promises`?

**Comment by mvano** [comment]
Note that things would be a little different if we were talking about `Promise<bool> isRegistered()` which seems even less appropriate to throw an exception for.

**Comment by jakearchibald** [comment]
http://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional

> What exactly you consider "exceptional" is up for debate, as always. But, you should always ask, before rejecting a promise: if this function was synchronous, would I expect a thrown exception under this circumstance? Or perhaps a failure value (like null, false, or undefined)?
> …
> Bad uses of rejections include:
> 
> When a value is asked for asynchronously and is not found: for example asyncMap.get("key") should return a promise for undefined when there is no entry for "key"

There's a big discussion over at https://github.com/slightlyoff/ServiceWorker/issues/374 where I fought for `caches.match` to reject if no match was found. I was talked around in the end.

**Comment by mvano** [comment]
Thanks for the references Jake. I think those together with `await` make a reasonable argument for resolving with `null`.

**Comment by martinthomson** [comment]
I assume that the absence of meta-information about the absence is addressed by querying some other API?  Like a [.permission](http://www.w3.org/TR/notifications/#dom-notification-permission) attribute perhaps?

**Comment by mounirlamouri** [comment]
Not sure what you mean. I don't think `getRegistration()` should pass information about the absence of information. If the website never registered, it will have no registration, this is definitely expected. If the website tries to register but the call failed, `register()` should pass information about the failure reason, not `getRegistration()`. WDYT?

**Comment by martinthomson** [comment]
If `getRegistration()` fails, one advantage of a rejection is that it gives you somewhere to hang the meta-information about that failure: is this because you are on an http:// origin?  Is this because the push server is down?  Is this because you haven't got consent?  Error codes determine what steps need to be taken to correct the error.

**Comment by martinthomson** [comment]
I'm sorry, is this suggesting an asymmetry between `getRegistration()` and `register()`.

**Comment by mounirlamouri** [comment]
`getRegistration()` should not try to register. It should return the current registration if any.

**Comment by martinthomson** [comment]
Is there any reason then that it can't be:

> `attribute PushRegistration registration;`

And therefore be entirely synchronous?

**Comment by jakearchibald** [comment]
Its value can be changed from both pages and workers, which run on different threads.

**Comment by jakearchibald** [comment]
> If getRegistration() fails, one advantage of a rejection is that it gives you somewhere to hang the meta-information about that failure: is this because you are on an http:// origin?

That won't happen, as this API sits on the ServiceWorker registration, which requires https. But yes, if there's a failure to even find out there's no registration, that should be a rejection (as it would be a throw in sync code).
